In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pseries = pd.Series([12, 13, 14, 15])

pseries

pseries.index = [
    'Canada',
    'France',
    'Germany',
    'India'
]

arr1 = np.array([1,2,3,4,5,6])
arr1

#use np.arange(n) to produce an array of n elements starting from zero
arr2 = np.arange(6)
arr2

arr1 + arr2

#use arr.astype() to convert array from one datatype to another
arr3 = arr1.astype(np.float64)
arr3

In [ ]:
arr3.dtype

In [ ]:
arr4 = np.arange(10)
calibers = np.array([.22,.270,.357], dtype = np.float64)
arr4
calibers

In [ ]:
arr4

In [ ]:
arr4.astype(calibers.dtype)

In [ ]:
arr4

In [ ]:
arr4[5:8]

In [ ]:
# !!!array slices are views on the original array. This means that the data
# is not copied, and any modifications to the view will be reflected in
# the source array.
arr5 = arr4[5:8]
arr5

arr5[1] = 5
arr5

arr5

arr4

In [ ]:
#bare slice '[:]' will assign to all values in an array
arr5[:] = 69
arr5

In [ ]:
arr4

In [ ]:
#to copy explicitly use .copy()
arr6 = arr4[0:3].copy()
arr6

In [ ]:
arr2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr2d

In [ ]:
#arr[startrow:endrow, startcol:endcol] exclusive of startrow and startcol 
#and inclusive of endrow and endcol
arr2d[:2,1:]

In [ ]:
arr2d[:0]

In [ ]:
arr2d[:,1:]

In [33]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [36]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [37]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [39]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [40]:
data[names != "Bob"]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [43]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [44]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [45]:
arr7 = np.zeros((8,4))
for i in range(8):
    arr7[i] = i
arr7

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [49]:
arr7 = np.arange(25).reshape((5,5))
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr7.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [54]:
np.sqrt(arr7)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

In [55]:
# numpy.meshgrid function takes two onedimensional
# arrays and produces two two-dimensional matrices corresponding to all
# pairs of (x, y) in the two arrays:   
points = np.arange(-5,5,0.01)
xs,ys = np.meshgrid(points,points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [56]:
ys.shape

(1000, 1000)

In [57]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [60]:
# numpy.where function is a vectorized version of the ternary expression-
# x if condition else y
np.where(data == 0, 'is zero',data)

array([['4', '7'],
       ['is zero', '2'],
       ['-5', '6'],
       ['is zero', 'is zero'],
       ['1', '2'],
       ['-12', '-4'],
       ['3', '4']], dtype='<U21')